### ISSUE TITLE
Issue with historical CA catch calculations

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/canary_2023#64]
I noticed during model exploration that my historical CA catches were not aligned very well with estimates from the last assessment. I realized that my code [here](https://github.com/pfmc-assessments/canary_2023/blob/162d6e6f84c9cce5387730ccabd05fb5094f0bec/code/canary_catches_for_model.R#L98-L99) mistakenly did not exclude NA when adding unknown and known catches, thus NAs were produced whereas there should be a value (the non-NA part of the sum). 

This causes lower estimates for primarily the NTWL fleet in the historical period. When the issue is fixed estimates are higher, below the figure shows old (solid line) versus corrected estimates (dashed line) for the TWL (black) and NTWL (red) fleet

![image](https://github.com/pfmc-assessments/canary_2023/assets/27824606/a985dfce-40d1-4e28-ac5c-fa486058bc96)

When compared to the last assessment (blue lines below) these corrected values (green lines below) are larger for the NTWL fleet, but smaller for the TWL fleet. It appears that the previous assessment added the UNKNOWN fleet landings that are more prevalent early on to the TWL fleet rather than apportion based on proportions between known TWL and NTWL landings. Also, the sum of my values are EXACTLY half the sum of the values from the 2015 assessment for 1916-1950, so my guess is something got double counted in the last assessment.

![image](https://github.com/pfmc-assessments/canary_2023/assets/27824606/8a712d7c-3808-490e-8ad5-1aaf9fed90c2)

![image](https://github.com/pfmc-assessments/canary_2023/assets/27824606/4191dea4-6780-4e18-8ac5-ac23d8e017de)

**Comment by robwm477** [comment]
Hi Brian,

Does this change the historical removals that the states needed to approve? I ask because the GMT used those historical removals to calculate our future catch projection assumptions. If there are updated historical removals, can you please share that with me?

Thank you,


Whitney Roberts| Marine Policy Analyst

Washington Department of Fish & Wildlife

E: ***@***.******@***.***> | T: (360) 902-2675

________________________________
From: Brian Langseth ***@***.***>
Sent: Friday, May 19, 2023 11:34 AM
To: pfmc-assessments/canary_2023 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pfmc-assessments/canary_2023] Issue with historical CA catch calculations (Issue #64)


External Email

I noticed during model exploration that my historical CA catches were not aligned very well with estimates from the last assessment. I realized that my code here<https://github.com/pfmc-assessments/canary_2023/blob/162d6e6f84c9cce5387730ccabd05fb5094f0bec/code/canary_catches_for_model.R#L98-L99> mistakenly did not exclude NA when adding unknown and known catches, thus NAs were produced.

This causes lower estimates for primarily the NTWL fleet in the historical period. When fixed they are higher, below the figure shows old (solid line) versus corrected estimates (dashed line) for the TWL (black) and NTWL (red) fleet

[image]<https://user-images.githubusercontent.com/27824606/239606013-a985dfce-40d1-4e28-ac5c-fa486058bc96.png>

When compared to the last assessment (blue lines below) these corrected values (green lines below) are larger for the NTWL fleet, but smaller for the TWL fleet. It appears that the previous assessment added the UNKNOWN fleet landings that are more prevalent early on to the TWL fleet rather than apportion based on proportions between known TWL and NTWL landings. Also, the sum of my values are EXACTLY half the sum of the values from the 2015 assessment for 1916-1950, so my guess is something got double counted in the last assessment.

[image]<https://user-images.githubusercontent.com/27824606/239606733-8a712d7c-3808-490e-8ad5-1aaf9fed90c2.png>

[image]<https://user-images.githubusercontent.com/27824606/239607124-4191dea4-6780-4e18-8ac5-ac23d8e017de.png>

**Comment by brianlangseth-NOAA** [comment]
You are observant Whitney and quick to see this. I am in the process of sending this to the states. I only noticed this today. I will cc you on that email exchange.

**Comment by robwm477** [comment]
Excellent, thank you!


Whitney Roberts| Marine Policy Analyst

Washington Department of Fish & Wildlife

E: ***@***.******@***.***> | T: (360) 902-2675

________________________________
